### ISSUE TITLE
Unable to import SQL - SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by harshallakare** [code-boxx/Storage-Boxx-PHP-Inventory-System#6]
**Describe the bug**
While installing , I get below error. 
Unable to import SQL - SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**To Reproduce**
 1) Paste code in /var/www/html/
2) access installtion page 
3) Fill all the required details and hit Go. 

**Expected behavior**

**Screenshots** 
![image](https://github.com/code-boxx/Storage-Boxx-PHP-Inventory-System/assets/37395949/e3ccef75-120d-4734-8c42-0d2947f8a116)

**Comment by code-boxx** [comment]
1) If I remember correct, the limit of 767 bytes has already been raised to over 3000 bytes since MYSQL 5.6 ~ 5.7.
2) You are either using a very outdated version of MYSQL (the current version is 8), or your host is severly limiting it.
3) Highly recommended - Update your MYSQL server.
4) Or, you can edit `lib/STORAGE-BOXX.sql` - Change `UTF8MB4` to `latin`, less all the key lengths.
5) Or, you can edit `my.ini` or `my.cnf` on your server to raise the limit.

**Comment by harshallakare** [comment]
Thank for your quick help and installation moved ahead but again stuck
here.

[image: image.png]

So sorry, i'm not from developer background but a linux user.

Regards,

Harshal Lakare
